version: '2'

services:
  app:
    image: abakpress/ruby:1.9.3
    environment:
      - SSH_AUTH_SOCK=/ssh/auth/sock
    command: make
    volumes:
      - '.:/app'
      - '../:/localgems'
      - ruby-gems:/gems
      - ssh-data:/ssh:ro
      - bundler-config:/root/.bundle

volumes:
  ruby-gems:
    external:
      name: gems-ruby193

  ssh-data:
    external:
      name: ssh_data

  bundler-config:
    external:
      name: bundler-config
